site_name: Programming Practices for Research in Econonomics - Foundations
pages:
- Getting Started: index.md
#- Terminology: terminology.md
- Command Line Tools: commandLine.md
- Text Editor: textEditor.md
- Git: gitInstall.md
- R: r.md
- Build Tools: snakemake.md
- Contact: contact.md
- Acknowledgements: acknowledgement.md

theme: readthedocs
markdown_extensions:
  - admonition
